hmcts/sds-toffee-recipes-service

build.gradle

Updating tomcat to 9.0.50 to fix vulnerability

DTSPO-2879 - Tomcat version vulnerability

---

infrastructure/main.tf

- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/DTSPO-2879
Update repo to add SS vnet and removed old database 
```
[ ] Yes
[ ] No
```

DTSPO-2879  updated database and removed secrets

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSPO-2879
passing keyvault details to postgress database
```
[ ] Yes
[ x] No
```

DTSPO-2879  added keyvault variables

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSPO-2879 Removed API module

DTSPO-2879 removed api module

---

charts/toffee-recipe-backend/values.stg.template.yaml

- DTSPO-2880 - adding stg values file
- DTSPO-2880 - adding stg values file

DTSPO 2880/stg values

---

charts/toffee-recipe-backend/values.stg.template.yaml

- DTSPO-2880 - adding stg values file
- DTSPO-2880 - adding stg values file
- DTSPO-2880 - Testing disable postgres_ssl_mode in stg

"DTSPO-2880 - Testing disable postgres_ssl_mode in stg"

---

charts/toffee-recipe-backend/values.aat.template.yaml
infrastructure/state.tf
infrastructure/versions.tf

Dtspo-4157  pining  azuread version to v1.x

---

infrastructure/state.tf

- Adding azuread provider
- Bumping azuread provider version

DTSPO-4613 - bump azuread provider

---

build.gradle
checkstyle.xml
src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/domain/Recipe.java
src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/domain/RecipeList.java
src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/ApplicationTests.java
src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/endpoint/RecipeControllerTest.java
src/test/resources/init.sql

bit hacky and a quick job but didn't want to spend too long on it for a test app

DTSPO-6151 Add code coverage

---

charts/apple-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPO-6533
Upgrade ingress version to be compatible with v1
```
[ ] Yes
[x] No
```

DTSPO-6533 Upgrade ingress version to v1

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPO-5981
Bump org.springframework.boot to 2.6.4
```
[ ] Yes
[X] No
```

Bump org.springframework.boot to 2.6.4

---

build.gradle
charts/toffee-recipe-backend/Chart.yaml
dependency-check-suppressions.xml

DTSPO-8276
Fix failing security checks
```
[ ] Yes
[X] No
```

DTSPO-8276 - Fix failing security checks

---

build.gradle
dependency-check-suppressions.xml

Try fix security warnings, fails locally with test containers not starting although prob unrelated

Update spring boot

---

build.gradle
charts/apple-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/values.dev.template.yaml
dependency-check-suppressions.xml

This fixes all the CVE errors and gets the build working again
```
[ ] Yes
[x] No
```

Update packages and helm chart to fix build

---

charts/toffee-recipe-backend/Chart.yaml
dependency-check-suppressions.xml

Update java chart version

---

charts/apple-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/Chart.yaml

Update chart release java to latest
```
[ ] Yes
[x] No
```

bump helm chart java to 4.0.13

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/DTSPO-7198
Security Scan Setup
```
[ ] Yes
[X] No
```

DTSPO-7198 - Security Scan Setup

---

infrastructure/main.tf

add host fqdn for flexible server in KV

---

Jenkinsfile_nightly

Branch doesn't exist anymore 
```
[ ] Yes
[x] No
```

Fix nightly builds

---

charts/apple-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/Chart.yaml

Troubleshooting 
Reverts hmcts/sds-toffee-recipes-service#156

Revert "Update Helm release java to v4.1.0"

---

Dockerfile

Manage app insights version with renovate
```
[ ] Yes
[x] No
```

Manage app insights with renovate

---

.github/CODEOWNERS

Adding a list of files that need to be ignore so renovate can auto merge it's PRs without code owners approval
```
[ ] Yes
[x] No
```

Ignore files that are updated by Renovate

---

charts/toffee-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/values.yaml

Migrating over to postgres flexible server 
```
[ ] Yes
[x] No
```

Migrate to PG flexible server

---

charts/toffee-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/values.yaml
infrastructure/main.tf

Migrated to flexible servers
Removed port and database secrets as they're not outputs in the flexible module and the app has defaults set in the [app config](https://github.com/hmcts/sds-toffee-recipes-service/blob/master/src/main/resources/application.yaml)
```
[ ] Yes
[x] No
```

DTSPO-13244 - remove single postgres instances

---

README.md
infrastructure/variables.tf

DUMMY.  Update README.md

---

charts/toffee-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/values.yaml
infrastructure/main.tf

[DTSPO-14390](https://tools.hmcts.net/jira/browse/DTSPO-14390)
Add source and destination for DMS migration testing
```
[ ] Yes
[X] No
```

DTSPO-14390: Add source and destination for DMS migration testing

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPO-14034
Update build.gradle to use gatling plugin instead of docker image
```
[ ] Yes
[x] No
```

DTSPO-14034 - Update gatling to use plugin

---

infrastructure/main.tf

[DTSPO-14390](https://tools.hmcts.net/jira/browse/DTSPO-14390)
Enable public_access for destination flexible server
```
[ ] Yes
[X] No
```

DTSPO-14390 - Enable public_access for destination flexible server

---

build.gradle

Reverts hmcts/sds-toffee-recipes-service#183

Revert "Update plugin org.springframework.boot to v3"

---

build.gradle

[DTSPO-14390](https://tools.hmcts.net/jira/browse/DTSPO-14390)
Update tomcat to fix security check
```
[ ] Yes
[X] No
```

DTSPO-14390 - Update tomcat to fix security check

---

infrastructure/main.tf

Reverts hmcts/sds-toffee-recipes-service#300

Revert "DTSPO-14390 - Remove destination server"

---

charts/toffee-recipe-backend/Chart.yaml
infrastructure/main.tf

[DTSPO-14390](https://tools.hmcts.net/jira/browse/DTSPO-14390)
Remove source and destination testing DBs
```
[ ] Yes
[X] No
```

DTSPO-14390 - Remove source and destination testing DBs

---

charts/toffee-recipe-backend/Chart.yaml
infrastructure/main.tf

Reverts hmcts/sds-toffee-recipes-service#317

Revert "DTSPO-14390 - Remove source and destination testing DBs"

---

charts/toffee-recipe-backend/Chart.yaml
infrastructure/main.tf

DTSPO-14390
Delete Single Server Source DB and Secrets

DTSPO-14390 - Delete Single Server Source DB and Secrets

---

charts/toffee-recipe-backend/Chart.yaml
infrastructure/main.tf

Reverts hmcts/sds-toffee-recipes-service#325

Revert "DTSPO-14390 - Delete Single Server Source DB and Secrets"

---

charts/apple-recipe-backend/Chart.yaml
charts/apple-recipe-backend/values.yaml
charts/toffee-recipe-backend/Chart.yaml
charts/toffee-recipe-backend/values.yaml

DTSPO-15411
Remove AAD Identity

remove aad identity

---

infrastructure/main.tf

Postgresql v15

---

infrastructure/main.tf
infrastructure/sbox.tfvars

See [DTSPO-24722](https://tools.hmcts.net/jira/browse/DTSPO-24722)
Test flex server restore procedure  via terraform

DTSPO-24722 - Test flex server restore via terraform

---

infrastructure/main.tf

See [DTSPO-24722](https://tools.hmcts.net/jira/browse/DTSPO-24722)
Add missing restore time

DTSPO-24722 - Test flex server restore via terraform - 2

---

infrastructure/main.tf

- Restoring stg server to a temporary server using PITR
- Will then test upgrading the temp server to pg16 via portal, then restore that server to a new server again

Create temporary restored server in aat

---

infrastructure/main.tf

- Adding storage size to restore server
- Required to do the restore

Add storage size to restore server

---

infrastructure/main.tf

- Restoring the upgraded temp server to the final restored server

Restore upgraded server

---

infrastructure/main.tf

- Setting zone to 3 on temp server as pipeline trying to change and failing

Set zone number to get pipeline to pass

---

infrastructure/main.tf

- Unable to restore server with `delegated_subnet_id` set so removing it

Removing delegated_subnet_id from restored server

---

infrastructure/main.tf

- Add lifecycle argument to ignore changes to `point_in_time_restore_time_in_utc`
- Update the code for the restored server so it matches what is deployed

Update code to match deployed server

---

build.gradle
charts/apple-recipe-backend/Chart.yaml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Fix failing builds due to Jitpack as well as old java chart 5.2.1.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

fix jitpack fail
